language: python

sudo: false

python:
  - "3.6"

script:
  - python check_releases.py

notifications:
  webhooks:
    urls:
      - http://ci-bot.satoshilabs.com:5000/travis
    on_success: always
    on_failure: always
    on_start: always
